exit_on_error() {
    exit 1
}
